package cli

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/Jackson2403/envseal/internal/config"
	"github.com/fatih/color"
	"github.com/spf13/cobra"
)

const hookMarker = "# Auto-generated by EnvSeal. Do not edit."

// hookPath returns the pre-commit hook path for the current repo.
func hookPath() string {
	return filepath.Join(".git", "hooks", "pre-commit")
}

// hookScript renders the POSIX shell pre-commit guard. secretsRe is a grep -E
// expression that flags lines that look like `NAME=<value>` with a value.
func hookScript(secretsRe string) string {
	return fmt.Sprintf(`#!/bin/sh
# Auto-generated by EnvSeal. Do not edit.
# To disable this check:  envseal hook uninstall
# To bypass a block:      git commit --no-verify

secrets_re='%s'

TMP="$(mktemp 2>/dev/null || mktemp -t envseal.XXXXXX)"
trap 'rm -f "$TMP"' EXIT

git diff --cached --name-only > "$TMP" 2>/dev/null || exit 0
test -s "$TMP" || exit 0

blocked=0

while IFS= read -r f; do
    [ -f "$f" ] || continue

    # 1. Committed environment file that isn't an example/test template.
    case "$f" in
        .env|.env.*|*.env)
            case "$f" in
                *.example*|*.test*) ;;
                *)
                    echo "envseal: BLOCKED commit: environment file '$f'"
                    blocked=1
                    continue
                    ;;
            esac
            ;;
    esac

    # 2. Added lines in any staged file that look like a secret assignment.
    if git show :"$f" 2>/dev/null | grep -Ei "$secrets_re" >/dev/null 2>&1; then
        echo "envseal: BLOCKED commit: '$f' may contain a secret value."
        blocked=1
    fi
done < "$TMP"

if [ "$blocked" -ne 0 ]; then
    echo ""
    echo "EnvSeal guard: refusing to commit what looks like a secret."
    echo "  - confirm the file really should be committed, then:"
    echo "       git commit --no-verify"
    echo "  - disable this guard permanently:"
    echo "       envseal hook uninstall"
    exit 1
fi
exit 0
`, secretsRe)
}

// hookSecretsRe builds a grep -E expression from the configured dangerous
// patterns, matching `NAME=<non-empty value>` lines (case-insensitive).
func hookSecretsRe(patterns []string) string {
	if len(patterns) == 0 {
		patterns = config.Default().Check.DangerousPatterns
	}
	var alts []string
	for _, p := range patterns {
		p = strings.ToLower(strings.TrimSpace(p))
		if p == "" {
			continue
		}
		// Allow snake, kebab, or plain forms of a pattern name.
		alts = append(alts, strings.ReplaceAll(p, "_", "[_-]"))
	}
	if len(alts) == 0 {
		alts = []string{"password", "secret", "token", "key", "credential"}
	}
	alt := strings.Join(alts, "|")
	return "[A-Za-z_][A-Za-z0-9_.-]*(" + alt + ")[A-Za-z0-9_.-]*[[:space:]]*=[[:space:]]*[^#[:space:]]"
}

func newHookCmd() *cobra.Command {
	var force bool
	cmd := &cobra.Command{
		Use:   "hook",
		Short: "Install or remove the .env commit guard",
		Long: `Manage a git pre-commit hook that blocks accidental commits of
.env files or files containing secret-looking values.`,
	}

	cmd.AddCommand(
		&cobra.Command{
			Use:   "install",
			Short: "Install the pre-commit guard",
			Args:  cobra.NoArgs,
			RunE: func(cmd *cobra.Command, args []string) error {
				cfg, err := config.Load(".")
				if err != nil {
					return err
				}
				if err := os.MkdirAll(filepath.Dir(hookPath()), 0o755); err != nil {
					return err
				}
				// Refuse to overwrite a non-envseal hook unless forced.
				if !force {
					if data, err := os.ReadFile(hookPath()); err == nil &&
						!strings.Contains(string(data), hookMarker) {
						return fmt.Errorf("%s already exists and was not created by EnvSeal; use --force to overwrite", hookPath())
					}
				}
				script := []byte(hookScript(hookSecretsRe(cfg.Check.DangerousPatterns)))
				if err := os.WriteFile(hookPath(), script, 0o755); err != nil {
					return err
				}
				fmt.Printf("Installed pre-commit guard at %s\n", hookPath())
				fmt.Println("It blocks .env files and secret-looking values. Remove with 'envseal hook uninstall'.")
				return nil
			},
		},
		&cobra.Command{
			Use:   "uninstall",
			Short: "Remove the pre-commit guard",
			Args:  cobra.NoArgs,
			RunE: func(cmd *cobra.Command, args []string) error {
				data, err := os.ReadFile(hookPath())
				if err != nil {
					if os.IsNotExist(err) {
						return fmt.Errorf("no pre-commit hook found at %s", hookPath())
					}
					return err
				}
				if !strings.Contains(string(data), hookMarker) {
					red := color.New(color.FgRed)
					red.Fprintln(os.Stderr, "Refusing: existing hook at "+hookPath()+" was not created by EnvSeal.")
					return fmt.Errorf("hook was not created by EnvSeal; remove it manually")
				}
				if err := os.Remove(hookPath()); err != nil {
					return err
				}
				fmt.Printf("Removed pre-commit guard at %s\n", hookPath())
				return nil
			},
		},
	)

	cmd.PersistentFlags().BoolVar(&force, "force", false, "overwrite an existing non-EnvSeal hook")
	return cmd
}
